// Generated by https://github.com/StirlingMarketingGroup/go2ts

// auth.go
export interface RegisterUserPayload {
    email: string;
    password: string;
}

export interface RegisterResponse {
    status: number;
    data?: {
        user: User;
    };
    error?: string;
}

export interface LoginUserPayload {
    email: string;
    password: string;
}

export interface LoginResponse {
    status: number;
    data?: {
        token: string;
        user: User;
    };
    error?: string;
}

export interface GetMeResponse {
    status: number;
    data?: {
        user: User;
    };
    error?: string;
}

// user.go
export enum UserRole {
    Default = "DEFAULT",
    Admin = "ADMIN",
}

export interface User {
    user_id: number;
    email: string;
    user_role: UserRole;
    last_logged_in: string;
    verified: boolean;
    created_at: string;
    updated_at: string;
}

export interface GetUserByIdResponse {
    status: number;
    data?: {
        user: User;
    };
    error?: string;
}

export interface DeleteUserResponse {
    status: number;
    data?: {
        message: string;
        user: User;
    };
    error?: string;
}

// benchmark.go
export enum AssetCategory {
    Cash = "CASH",
    Bills = "BILLS",
    STB = "STB",
    ITB = "ITB",
    LTB = "LTB",
    Commodities = "COMMODITIES",
    Gold = "GOLD",
    REITS = "REITS",
    TSM = "TSM",
    DLCB = "DLCB",
    DLCG = "DLCG",
    DLCV = "DLCV",
    DLCM = "DLCM",
    DMCB = "DMCB",
    DMCG = "DMCG",
    DMCV = "DMCV",
    DMCM = "DMCM",
    DSCG = "DSCG",
    DSCB = "DSCB",
    DSCV = "DSCV",
    DSCM = "DSCM",
    ILCB = "ILCB",
    ILCG = "ILCG",
    ILCV = "ILCV",
    ILCM = "ILCM",
    IMCB = "IMCB",
    IMCG = "IMCG",
    IMCV = "IMCV",
    IMCM = "IMCM",
    ISCB = "ISCB",
    ISCG = "ISCG",
    ISCV = "ISCV",
    ISCM = "ISCM",
    Crypto = "CRYPTO",
    Other = "OTHER",
}

export interface AssetAllocationPct {
    category: AssetCategory;
    percent: number;
}

export interface Benchmark {
    benchmark_id: number;
    name: string;
    description?: string;
    asset_allocation: AssetAllocationPct[];
    std_dev_pct?: number;
    real_return_pct?: number;
    drawdown_yrs?: number;
    rec_rebalance_threshold_pct?: number;
    is_deprecated?: boolean;
    user_id: number;
    created_at: string;
    updated_at: string;
}

export interface CreateBenchmarkPayload {
    name: string;
    description?: string;
    asset_allocation: AssetAllocationPct[];
    std_dev_pct?: number;
    real_return_pct?: number;
    drawdown_yrs?: number;
    rec_rebalance_threshold_pct?: number;
    is_deprecated?: boolean;
}

export interface CreateBenchmarkResponse {
    status: number;
    data?: {
        benchmark: Benchmark;
    };
    error?: string;
}

export interface GetBenchmarksResponse {
    status: number;
    data?: {
        benchmarks: Benchmark[];
        pagination: PaginationMetadata;
    };
    error?: string;
}

export interface GetBenchmarkResponse {
    status: number;
    data?: {
        benchmark: Benchmark;
    };
    error?: string;
}

export interface UpdateBenchmarkPayload {
    name: string;
    description?: string;
    asset_allocation: AssetAllocationPct[];
    std_dev_pct?: number;
    real_return_pct?: number;
    drawdown_yrs?: number;
    rec_rebalance_threshold_pct?: number;
    is_deprecated?: boolean;
}

export interface UpdateBenchmarkResponse {
    status: number;
    data?: {
        benchmark: Benchmark;
    };
    error?: string;
}

export interface DeleteBenchmarkResponse {
    status: number;
    data?: {
        message: string;
        benchmark: Benchmark;
    };
    error?: string;
}

// account.go
export enum TaxShelter {
    Taxable = "TAXABLE",
    Traditional = "TRADITIONAL",
    Roth = "ROTH",
    HSA = "HSA",
    FiveTwentyNine = "529",
}

export interface Account {
    account_id: number;
    name: string;
    description?: string;
    tax_shelter: TaxShelter;
    institution: string;
    is_deprecated?: boolean;
    user_id: number;
    created_at: string;
    updated_at: string;
}

export interface CreateAccountPayload {
    name: string;
    description?: string;
    tax_shelter: TaxShelter;
    institution: string;
    is_deprecated?: boolean;
}

export interface CreateAccountResponse {
    status: number;
    data?: {
        account: Account;
    };
    error?: string;
}

export interface GetAccountsResponse {
    status: number;
    data?: {
        accounts: Account[];
        pagination: PaginationMetadata;
    };
    error?: string;
}

export interface GetAccountResponse {
    status: number;
    data?: {
        account: Account;
    };
    error?: string;
}

export interface UpdateAccountPayload {
    name: string;
    description?: string;
    tax_shelter: TaxShelter;
    institution: string;
    is_deprecated?: boolean;
}

export interface UpdateAccountResponse {
    status: number;
    data?: {
        account: Account;
    };
    error?: string;
}

export interface DeleteAccountResponse {
    status: number;
    data?: {
        message: string;
        account: Account;
    };
    error?: string;
}

// holding.go
export interface Holding {
    holding_id: number;
    name: string;
    ticker?: string;
    asset_category: AssetCategory;
    expense_ratio_pct?: number;
    maturation_date?: string;
    interest_rate_pct?: number;
    is_deprecated?: boolean;
    user_id: number;
    created_at: string;
    updated_at: string;
}

export interface CreateHoldingPayload {
    name: string;
    ticker?: string;
    asset_category: AssetCategory;
    expense_ratio_pct?: number;
    maturation_date?: string;
    interest_rate_pct?: number;
    is_deprecated?: boolean;
}

export interface CreateHoldingResponse {
    status: number;
    data?: {
        holding: Holding;
    };
    error?: string;
}

export interface GetHoldingsResponse {
    status: number;
    data?: {
        holdings: Holding[];
        pagination: PaginationMetadata;
    };
    error?: string;
}

export interface GetHoldingResponse {
    status: number;
    data?: {
        holding: Holding;
    };
    error?: string;
}

export interface UpdateHoldingPayload {
    name: string;
    ticker?: string;
    asset_category: AssetCategory;
    expense_ratio_pct?: number;
    maturation_date?: string;
    interest_rate_pct?: number;
    is_deprecated?: boolean;
}

export interface UpdateHoldingResponse {
    status: number;
    data?: {
        holding: Holding;
    };
    error?: string;
}

export interface DeleteHoldingResponse {
    status: number;
    data?: {
        message: string;
        holding: Holding;
    };
    error?: string;
}

// snapshot.go
export interface Snapshot {
    snap_id: number;
    description?: string;
    snap_date: string;
    total: number;
    weighted_er_pct: number;
    rebalance_threshold_pct?: number;
    benchmark_id?: number;
    value_order?: number[];
    user_id: number;
    created_at: string;
    updated_at: string;
}

export interface ResourcesGrouped {
    fields: string[];
    total: number[];
}

export interface MaturationDateResource {
    account_name: string;
    holding_name: string;
    asset_category: string;
    interest_rate_pct: number;
    maturation_date: string;
    total: number;
    skip_rebalance: boolean;
}

export interface LiquidityResource {
    account_name: string;
    holding_name: string;
    asset_category: string;
    ticker: string;
    institution: string;
    tax_shelter: string;
    total: number;
}

export interface AssetAllocation {
    category: string;
    value: number;
}

export interface CreateSnapshotPayload {
    snap_date: string;
    description?: string;
    snapshot_values: CreateSnapshotValuePayload[];
    rebalance_threshold_pct?: number;
    benchmark_id?: number;
}

export interface CreateSnapshotResponse {
    status: number;
    data?: {
        snapshot: Snapshot;
        snapshot_values: SnapshotValue[];
    };
    error?: string;
}

export interface GetSnapshotResponse {
    status: number;
    data?: {
        snapshot: Snapshot;
        snapshot_values: SnapshotValue[];
        accounts: Account[];
        holdings: Holding[];
    };
    error?: string;
}

export interface GetSnapshotsResponse {
    status: number;
    data?: {
        snapshots: Snapshot[];
        pagination: PaginationMetadata;
    };
    error?: string;
}

export interface GetSnapshotAccountsResponse {
    status: number;
    data?: {
        accounts_grouped: ResourcesGrouped;
        field_type: string;
    };
    error?: string;
}

export interface GetSnapshotHoldingsResponse {
    status: number;
    data?: {
        holdings_grouped: ResourcesGrouped;
        field_type: string;
    };
    error?: string;
}

export interface GetSnapshotMaturationDateResponse {
    status: number;
    data?: {
        resources: MaturationDateResource[];
        field_type: string;
        maturation_start: string;
        maturation_end: string;
    };
    error?: string;
}

export interface GetSnapshotLiquidityResponse {
    status: number;
    data?: {
        resources: LiquidityResource[];
        liquid_total: string;
        field_type: string;
    };
    error?: string;
}

export interface GetSnapshotRebalanceResponse {
    status: number;
    data?: {
        target_allocation?: AssetAllocation[];
        current_allocation?: AssetAllocation[];
        change_required?: AssetAllocation[];
        rebalance_deviation_pct: number;
        needs_rebalance: boolean;
        snapshot_total: number;
        snapshot_total_omit_skips: number;
    };
    error?: string;
}

export interface UpdateSnapshotPayload {
    snap_date: string;
    description?: string;
    rebalance_threshold_pct?: number;
    benchmark_id?: number;
    value_order?: number[];
}

export interface UpdateSnapshotResponse {
    status: number;
    data?: {
        snapshot: Snapshot;
    };
    error?: string;
}

export interface UpdateSnapshotValueOrderPayload {
    value_order: number[];
}

export interface UpdateSnapshotValueOrderResponse {
    status: number;
    data?: {
        snapshot: Snapshot;
    };
    error?: string;
}

export interface DeleteSnapshotResponse {
    status: number;
    data?: {
        message: string;
        snapshot: Snapshot;
    };
    error?: string;
}

// snapshot_value.go
export interface SnapshotValue {
    snap_val_id: number;
    snap_id: number;
    account_id: number;
    holding_id: number;
    total: number;
    skip_rebalance?: boolean;
    user_id: number;
    created_at: string;
    updated_at: string;
}

export interface CreateSnapshotValuePayload {
    account_id: number;
    holding_id: number;
    total: number;
    skip_rebalance?: boolean;
}

export interface CreateSnapshotValueResponse {
    status: number;
    data?: {
        snapshot_value: SnapshotValue;
    };
    error?: string;
}

export interface GetSnapshotValuesResponse {
    status: number;
    data?: {
        snapshot_values: SnapshotValue[];
    };
    error?: string;
}

export interface GetSnapshotValueResponse {
    status: number;
    data?: {
        snapshot_value: SnapshotValue;
    };
    error?: string;
}

export interface UpdateSnapshotValuePayload {
    account_id: number;
    holding_id: number;
    total: number;
    skip_rebalance?: boolean;
}

export interface UpdateSnapshotValueResponse {
    status: number;
    data?: {
        snapshot_value: SnapshotValue;
        snapshot_total: number;
        snapshot_weighteder: number;
    };
    error?: string;
}

export interface DeleteSnapshotValueResponse {
    status: number;
    data?: {
        snapshot_value: SnapshotValue;
        snapshot_total: number;
        snapshot_weighteder: number;
        message: string;
    };
    error?: string;
}

// pagination.go
export interface PaginationMetadata {
    current_page: number;
    page_size: number;
    total_items: number;
}